<?php
define('ORBITR_DAILY_ARCHVIES', __('Daily Archives', 'orbitr'));
define('ORBITR_MONTHLY_ARCHIVES', __('Monthly Archives', 'orbitr'));
define('ORBITR_YEARLY_ARCHIVES', __('Yearly Archives', 'orbitr'));
define('ORBITR_BLOG_ARCHIVES', __('Blog Archives', 'orbitr'));
define('ORBITR_MOST_USED_CATEGORIES', __('Most Used Categories', 'orbitr'));
define('ORBITR_TRY_LOOKING_MONTHLY_ARCHIVES', __('Try Looking Monthly Archives', 'orbitr'));
define('ORBITR_OLDER_POSTS', __('&larr; Older Posts', 'orbitr'));
define('ORBITR_NEWER_POSTS', __('Newer posts &rarr;', 'orbitr'));
define('ORBITR_RETURN_TO_PREVIUS', __('Return to %s', 'orbitr'));
define('ORBITR_BY_AUTHOR', __('By %2$s', 'orbitr'));
define('ORBITR_VIEW_ALL_POST_BY', __('View all posts by %s', 'orbitr'));
define('ORBITR_PUBLISHED_BY_AUTHOR', __('Published %2$s', 'orbitr'));
define('ORBITR_FULL_SIZE_IS_PIXEL', __('Full size is %s pixels', 'orbitr'));
define('ORBITR_LINK_TO_FULL_SIZE', __('Link to full-size image', 'orbitr'));
define('ORBITR_EDIT', __('Edit', 'orbitr'));
define('ORBITR_BOOKMARK_THE', __('Bookmark the', 'orbitr'));
define('ORBITR_PERMALINK', __('&nbsp;permalink', 'orbitr'));
define('ORBITR_PAGES_COLON', __('Pages:', 'orbitr'));
define('ORBITR_AUTHOR_ARCHIVES', __('All posts by : %s', 'orbitr'));
define('ORBITR_ABOUT_AUTHOR', __('About %s', 'orbitr'));
define('ORBITR_HOME', __('Home', 'orbitr'));
define('ORBITR_SORRY_NO_POST_MATCHED_YOUR_CRETERIA', __('Sorry no post matched your criteria', 'orbitr'));
define('ORBITR_PRIMARY_WIDGET', __('Primary Widget Area', 'orbitr'));
define('ORBITR_THE_PRIMARY_WIDGET', __('The primary widget area', 'orbitr'));
define('ORBITR_SECONDRY_WIDGET', __('Secondary Widget Area', 'orbitr'));
define('ORBITR_THE_SECONDRY_WIDGET', __('The secondary widget area', 'orbitr'));
define('ORBITR_FIRST_FOOTER_WIDGET', __('First Footer Widget Area', 'orbitr'));
define('ORBITR_THE_FIRST_FOOTER_WIDGET', __('The first footer widget area', 'orbitr'));
define('ORBITR_SECONDRY_FOOTER_WIDGET', __('Second Footer Widget Area', 'orbitr'));
define('ORBITR_THE_SECONDRY_FOOTER_WIDGET', __('The second footer widget area', 'orbitr'));
define('ORBITR_THIRD_FOOTER_WIDGET', __('Third Footer Widget Area', 'orbitr'));
define('ORBITR_THE_THIRD_FOOTER_WIDGET', __('The third footer widget area', 'orbitr'));
define('ORBITR_FOURTH_FOOTER_WIDGET', __('Fourth Footer Widget Area', 'orbitr'));
define('ORBITR_THE_FOURTH_FOOTER_WIDGET', __('The fourth footer widget area', 'orbitr'));
define('ORBITR_MAIN_MENU', __('Main Menu', 'orbitr'));
define('ORBITR_CATEGORIES', __('Categories', 'orbitr'));
define('ORBITR_ARCHIVES', __('Archives', 'orbitr'));
define('ORBITR_CONTACT_US', __('Contact Us', 'orbitr'));
define('ORBITR_LOCATION_MAP', __('Location Map', 'orbitr'));
